<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="rvkinfotech-Lenovo-G50-70" failures="1" tests="4" name="Test" time="32.331" errors="0" timestamp="2021-10-28T19:12:10 IST">
  <testcase classname="com.hrm.login.tests.LoginTests" name="withValidUserNameAndPassword" time="4.672"/>
  <testcase classname="com.hrm.login.tests.LoginTests" name="withInvalidUserNameAndPassword" time="1.613"/>
  <testcase classname="com.hrm.login.tests.LoginTests" name="withvalidUserNameAndInvalidPassword" time="1.834">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at com.hrm.login.tests.LoginTests.withvalidUserNameAndInvalidPassword(LoginTests.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- withvalidUserNameAndInvalidPassword -->
  <testcase classname="com.hrm.login.tests.LoginTests" name="withInvalidUserNameAndValidPassword" time="1.536"/>
</testsuite> <!-- Test -->
